# Generated by Django 3.1.3 on 2020-11-21 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bourse', '0002_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('nombre', models.IntegerField(default=0)),
                ('cours', models.FloatField(default=0)),
                ('type', models.CharField(choices=[('Achat', 'ACHAT'), ('Vente', 'VENTE')], default='Achat', max_length=10)),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bourse.stock')),
            ],
        ),
    ]
