# Generated by Django 3.1.3 on 2020-11-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourse', '0005_auto_20201121_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fees',
            field=models.FloatField(default=0),
        ),
    ]
