# Generated by Django 3.1.3 on 2020-11-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bourse', '0006_transaction_fees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='fees',
            new_name='total_value',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='value',
        ),
    ]
