# Generated by Django 3.1.3 on 2020-11-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourse', '0007_auto_20201121_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(),
        ),
    ]
