# Generated by Django 3.1.3 on 2020-11-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourse', '0008_auto_20201121_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlphaVantageApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
            ],
        ),
    ]
