# Generated by Django 3.1.3 on 2020-11-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourse', '0009_alphavantageapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='monitored',
            field=models.BooleanField(default=True),
        ),
    ]
