# Generated by Django 3.1.3 on 2020-11-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourse', '0010_stock_monitored'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
